### ISSUE TITLE
Is this compatible with the reforged update?

### ISSUE THREAD

**Issue by PointMeAtTheDawn** [runi95/wc3-slk-edit-electron#3]

**Comment by runi95** [comment]
It hasn't been tested with the reforged update yet and it doesn't have any of the reforged models and icons.

**Comment by runi95** [comment]
You can use Promises' Json Editor https://github.com/Promises/Warcraft3-Json-Editor
It loads SLK files and outputs JSON files that can then be converted back to SLK with his JSON to SLK converter https://github.com/Promises/WC3-json-to-slk
